name: sekp
description: "Sistem Etos Kerja"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

  # Firebase core
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.0

  # Storage & image
  firebase_storage: ^12.4.10
  image_picker: ^1.0.4

  printing: ^5.11.0
  excel: ^3.0.0
  path_provider: ^2.1.2
  open_file: ^3.3.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/akbar.jpeg
